/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as CreateRouteImport } from "./routes/create";
import { Route as PollIdRouteImport } from "./routes/poll.$id";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const CreateRoute = CreateRouteImport.update({
  id: "/create",
  path: "/create",
  getParentRoute: () => rootRouteImport,
} as any);
const PollIdRoute = PollIdRouteImport.update({
  id: "/poll/$id",
  path: "/poll/$id",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/create": typeof CreateRoute;
  "/poll/$id": typeof PollIdRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/create": typeof CreateRoute;
  "/poll/$id": typeof PollIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/create": typeof CreateRoute;
  "/poll/$id": typeof PollIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/create" | "/poll/$id";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/create" | "/poll/$id";
  id: "__root__" | "/" | "/create" | "/poll/$id";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  CreateRoute: typeof CreateRoute;
  PollIdRoute: typeof PollIdRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/create": {
      id: "/create";
      path: "/create";
      fullPath: "/create";
      preLoaderRoute: typeof CreateRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/poll/$id": {
      id: "/poll/$id";
      path: "/poll/$id";
      fullPath: "/poll/$id";
      preLoaderRoute: typeof PollIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  PollIdRoute: PollIdRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
